config/routes.rb
Rails.application.routes.draw do



  root 'home#index'

  resources :home 
  resources :comments 
  resources :users
  resources :posts
  resources :sessions, except: [:destroy]
  delete '/sessions' => 'sessions#destroy', as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end   

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :post, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

helper_method :current_user, :user_signed_in_?, :authenticate

  def authenticate
  	if !session[:user_id]
  	redirect_to new_session_path
  	end
  end

  def current_user
    # session[:user_id] = nil
  	if user_signed_in_?
  		User.find(session[:user_id])
  	end
  end

  def user_signed_in_?
    # session[:user_id] = nil
  	!session[:user_id].nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :authenticate, only: [:new, :create, :edit, :update, :destroy]

  def index
    @comment_all = Comment.all
  end

  def new
    @comment = Comment.new
  end


 def create
    respond_to do |format|
      @comment = current_user.comments.create(comment_params)
      format.js
      format.html {redirect_to posts_path}
      end 
  end

  # def create
  #   # binding.pry
  #   current_user.comments.create(comment_params)
  #   redirect_to posts_path
  # end

  def show
    # @post_all = Post.all
    # @comment_all = Comment.all
    @comment = Comment.find(params[:id])
  end

  def edit
    @body_class = 'show'
    @comment = Comment.find(params[:id])
    # redirect_to @post
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to posts_path
  end

  def destroy
    Comment.find(params[:id]).delete
    redirect_to posts_path
  end

private

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @body_class = 'home'
  	if user_signed_in_?
  	 	#  	opt 1 redirect_to current_user
  	 	@user = current_user 
  	 	redirect_to @user
    end
  	#  else
  	#  	# redirect_to new_session_path
  	#  	redirect_to root_path
  	# end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate, only: [:new, :create, :edit, :update, :destroy]

  def index
    @body_class = 'blog'
    @post_all = Post.all
    @comment = Comment.new  
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.create(post_params)
    redirect_to @user
  end

  def show
    @user = current_user
    @post_all = Post.all
    @post = Post.find(params[:id])
  end

  def edit
    @body_class = 'edit_posts'
    @post = Post.find(params[:id])
  end

  def update
    @body_class = 'update_posts'
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to current_user 
  end
  # opt 2
  #  def update
  #   @body_class = 'update_posts'
  #   @post = Post.find(params[:id])
  #   @post.update(post_params)
  #   redirect_to current_user
  # end

  def destroy
    @user = current_user
    @post = Post.find(params[:id]).destroy
    redirect_to @user
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
    @body_class = 'sign_in'
  end

  def create
    @user = User.find_by(session_params)
    if @user
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:alert] = 'email or password is incorrect'
      redirect_to new_session_path
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

private

    def session_params
    params.require(:login).permit(:email, :password)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate, only: [:edit, :update, :destroy]  
# validates :email, uniqueness, :true

  def index
    @user_all = User.all
  end

  def new
      @body_class = 'create_account'
      @user = User.new
    # byebug #stop here interact with this line in the terminal
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Account Created'
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:alert] = 'Account not created'
      redirect_to new_user_path
    end
  end

  def show
    @body_class = 'profile'
    @user_one = current_user
    @user = User.find(params[:id])
    @user_all = User.all.reject{|user| user == @user_one}
  # byebug
  end

  def edit
    @body_class = 'edit_account'
    @user = current_user
    @user = User.find(params[:id])
  end

  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end


  def destroy
    @user = current_user
    @user = User.find(params[:id]).destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # opt 2
  # def destroy
  #   # to check its working
  #   # puts "got"
  #   respond_to do |format|
  #     User.find(params[:id]).destroy
  #     session[:user_id] = nil
  #     format.js
  #     format.html {render 'home/index'}
  #   end
  # end

private


  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commments_helper.rb
module CommmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="padding"><%= comment.comment %></p>
  <span class="small">Posted by: <%= comment.user.name %> </span>
  <span class="small"><%= comment.created_at.to_formatted_s(:short) %></span>
  <% if current_user == comment.user %>
    <%= link_to image_tag("delete-icon.png", class: "format"), comment,  method: :delete %>
    <%= link_to image_tag("edit.png", class: "format"),edit_comment_path(comment) %>
  <% end %>
</div>

app/views/comments/create.html.erb
<!-- create comment -->

<div class="container-fluid">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p top">
    	<div class="header_two">
         <h4 >create comment </h4>
    	</div>
    </div>
    <div class="col">
    </div>
  </div>
<!-- end of row -->
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding">
        <%= form_with model: @comment do |f| %>
          <%= f.label :Comment %>
          <%= f.text_field :comment, placeholder: 'comment' %>
          <%= f.submit "Add Comment", class: "btn btn-primary" %>
        <% end %>
      </div>
     </div>
   <div class="col">
   </div>
  </div>
  <!-- end of row -->
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding padding_b">
        <div>
          <%= link_to "My Profile", current_user, class: "btn btn-primary" %>
      </div>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$('#' + window.comment_section).prepend("<%= j render @comment %>");
$('.new_comment').trigger('reset');

app/views/comments/edit.html.erb
<!-- edit comment -->

<div class="container-fluid">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p top">
    	<div class="header">
		    <h2>Edit comments</h2>
  		  <p>Enter the changes you wish to make in your comment.</p>
    	</div>
    </div>
    <div class="col">
    </div>
  </div>
<!-- end of row -->
   <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding">
       <%= form_with model: @comment do |f| %>
          <%= f.label :Comment %>
          <%= f.text_field :comment, placeholder: 'comment', class: "form-control" %>
          <br>
          <%= f.submit "Update Comment", class: "btn btn-primary", id: "c_button" %>
        <% end %>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
<!-- end of row -->
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding padding_b">
        <%= link_to "Delete Comment", @comment, method: :delete, class: "btn btn-success" %>
      </div>
     </div>
     <div class="col">
     </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding">
        <%= link_to "Blog", posts_path, class: "btn btn-primary" %>
      </div>
     </div>
     <div class="col">
     </div>
  </div>
   <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding padding_b">
         <%= link_to "My Profile", current_user, class: "btn btn-primary" %>
      </div>
     </div>
     <div class="col">
     </div>
  </div>
</div>

app/views/comments/index.html.erb
if I want to show all comments

app/views/home/index.html.erb
  <div class="container-fluid">
    <div class="row">
      <div class="col">
      </div>
      <div class="col-6 header_two background">
       <h1>Adventures in Italy</h1>
      </div>
      <div class="col">
      </div>
    </div>
    <div class="row">
      <div class="col">
      </div>
      <div class="col-6">
       <img id="image" src="img/rome_006.jpg" alt="">
      </div>
      <div class="col">
      </div>
    </div>
     <div class="row">
      <div class="col">
      </div>
      <div class="col-6">
        <div class="content background">
          <div class="spacing">
             <h4>About Us</h4>
             <p>Travel like a local. This blog is to help make traveling around Italy easier and more fun!</p>
           </div>
        </div>
      </div>
      <div class="col">
      </div>
    </div>
     <div class="row">
      <div class="col">
      </div>
      <div class="col-6">
        <div class="content background">
          <div class="spacing">
            <h4>Your Experiance</h4>
            <p>With this blog you will find comments about the best way to travel when going to Italy. Login or create an account to post your do's and dont's when traveling to Italy.</p>
          </div>
        </div>
      </div>
      <div class="col">
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= @body_class %>">
 

    <nav>
      <ul class="nav">
        <% if user_signed_in_? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
             <%= link_to "Profile", current_user, class: "nav-link" %>
          </li>
          <li class="nav-item">
             <%= link_to "Blog", posts_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
             <%= link_to "Log Out", logout_path, method: :delete,  class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
           <%= link_to "Blog", posts_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_session_path, id:"sign_in_button", class: "lp-navbar__button lp-navbar__button--fixed btn btn--secondary" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Account", new_user_path, id:"sign_in_button", class: "lp-navbar__button lp-navbar__button--fixed btn btn--secondary" %>
          </li>
        <% end %>
      </ul>
    </nav>
      <%= yield %>
      
      <div class="push"></div>
      <footer class="footer">
      <ul class="nav justify-content-center">
        <% if user_signed_in_? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", current_user, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Blog", posts_path, class: "nav-link active" %>
          </li>
    
          <li class="nav-item">
            <%= link_to "Log Out", logout_path, method: :delete,  class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Blog", posts_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
               <%= link_to "Login", new_session_path, id:"sign_in_button", class: "lp-navbar__button lp-navbar__button--fixed btn btn--secondary" %>
          </li>
          <li class="nav-item">
               <%= link_to "Create Account", new_user_path, id:"sign_in_button", class: "lp-navbar__button lp-navbar__button--fixed btn btn--secondary" %>
          </li>
         <% end %>
      </ul>
    </footer>
  </body>
</html>

app/views/posts/_post.html.erb
<!-- render same info over different pages -->
<div class="post">
	<p class="font spacing"> <%= post.title %></p>
  <p><%= post.content %></p>
  <!-- delete all posts -->
  <span class="small">Posted by: <%= post.user.name %> </span> 
  <span class="small">on <%= post.created_at.to_formatted_s(:short) %></span>
   <div> 
      <% if user_signed_in_? %>
        <%= form_with model: @comment, class: "new_comment" do |f| %>
          <%= f.text_field :comment, placeholder: 'comment', class: "form-control" %>
          <%= f.hidden_field :post_id, :value => post.id %>
          <%= f.submit "add", :disable_with => 'adding...', class: "btn btn-primary", id: "update", remote: true  %>
        <% end %>
      <% end %>
    </div>
    <div class="comments" id="post-<%= post.id %>">
      <% post.comments.reverse.each do |comment| %>
        <%= render comment %>
      <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<!-- edit posts -->

<div class="container-fluid">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p top">
    	<div class="header_two">
		    <h2>Edit Posts</h2>
  		  <p>Enter the changes you wish to make in your post.</p>
    	</div>
    </div>
    <div class="col">
    </div>
  </div>
<!-- end of row -->
   <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding">
         <%= form_with model: @post do |f| %>
          <%= f.label :Title %>
          <br>
          <%= f.text_field :title, placeholder: 'title', class: "form-control", id: "title" %>
          <br>
           <%= f.label :Content %>
           <br>
          <%= f.text_field :content, placeholder: 'content', class: "form-control" %>
          <br>
            <%= f.submit "Update Post", id:"button_three", class: "btn btn-primary, update btn btn-primary" %>
          <% end %>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
<!-- end of row -->
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding padding_b">
        <%= link_to "Delete Post", @post, method: :delete, remote: true, class: "btn btn-success d_post" %>
      </div>
     </div>
     <div class="col">
     </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding padding_b">
        <%= link_to "My Profile", current_user, class: "btn btn-primary" %>
      </div>
     </div>
     <div class="col">
     </div>
  </div>
</div>

app/views/posts/index.html.erb
<!-- <div class="posts"> -->

<!-- how your post layout should look -->
<%# @post.each do |post| %>
<%# render post %>
<%# end %>
<!-- </div> -->

<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col-6 header background">
      <h1>Adventures in Italy</h1>
    </div>
    <div class="col"></div>
  </div>
  <!-- end of row -->
  <div class="row">
    <div class="col-6 offset-sm-3 background_p">
      <div class="padding_b">
        <h4>Blog Posts</h4>
      </div>
      <div class="posts post_o padding">
        <% @post_all.each do |post| %>
          <%= render post %>
           
        <% end %>
      </div>
    </div>
  </div> <!-- .row -->
  <div class="row">
    <div class="col-6 offset-sm-3 background_p"></div>
  </div> <!-- end of row -->
</div> <!-- end of container

app/views/users/_form.html.erb
  <%= form_with model: @user do |f| %>
		<%= f.label :name %>
    <%= f.text_field :name, placeholder: 'name', class: "form-control", id: "name" %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: 'email', class: "form-control", id: "exampleInputEmail1", ariadescribedby: "emailHelp" %>
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: 'password', class: "form-control", id: "exampleInputPassword1" %>
</div>	

app/views/users/_user.html.erb
<div>
	
  <% link_to "Delete Account", @user, method: :delete, remote: true, class: "btn btn-success" %>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p top">
    	<div class="header_two">
		    <h2>Edit Profile</h2>
  		  <p>Enter the changes you wish to make in your account.</p>
        <p>Your current information</p>
        <div class="left">
           <p><strong>Name:</strong> <%= @user.name %></p>
           <p><strong>Email:</strong> <%= @user.email %></p>
           <p><strong>Password:</strong> <%= @user.password %></p>
        </div>
    	</div>
    </div>
    <div class="col">
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding">
        <div class="form-group">
            <%= form_with model: @user do |f| %>
              <%= f.label :name %>
              <br>
              <%= f.text_field :name, class: "font", placeholder: 'name', class: "form-control", id: "name" %>
                <br>
              <%= f.label :email, class: "font" %>
              <br>
              <%= f.text_field :email, placeholder: 'email', class: "form-control", id: "exampleInputEmail1", ariadescribedby: "emailHelp" %>
              <br>
              <%= f.label :password, class: "font" %>
                <br>
              <%= f.password_field :password, placeholder: 'password', class: "form-control", id: "exampleInputPassword1" %>
                <br>
              <%= f.submit "Update Account", id: "button", class: "btn btn-primary" %>
            <% end %>
        </div>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding padding_b">
        <%= link_to "Delete Account", @user, method: :delete, remote: true, class: "btn btn-success destroy" %>
			</div>
     </div>
     <div class="col">
     </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding padding_b">
        <%= link_to "My Profile", current_user, class: "btn btn-primary" %>
      </div>
     </div>
     <div class="col">
     </div>
  </div>
</div>

app/views/users/index.html.erb
<!-- shows all users -->

<div class="container-fluid">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p top">
		  <div class="header_two">
         <h4><%= @user.name %>'s Profile</h4>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding">
         <h4>Account Details</h4>
          <p class="left">Email: <%= @user.email %> </p>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div>
        <h4 class="padding_b">Posts</h4>
        <div class="posts padding left">
          <div>
            <% @user.posts.each do |post| %>
              <p class="font"><%= post.title %></p>
              <p class="font"><%= post.content %></p>
              <div class="small">
                  <span>Posted by: <%= @user.name %> </span>
                  <span>on <%= post.created_at.to_formatted_s(:short) %></span>
                  <!-- <span class="reaction-button"></span>comment -->
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="background_p padding">
        <h4 class="padding">Fellow Travelers</h4>
          <div class="size">
            <% @user_all.each do |user| %>
              <p class="font top">
                <a href="/show/<%= user.id %>"><%= user.name %></a></p>
            <% end %>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding padding_b">
      <a href="/profile" class="btn btn-primary">My Profile</a>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <!-- <div class="padding padding_b">
      </div> -->
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/users/new.html.erb
<!-- create account -->
<div class="container">
  <div class="row">
    <div class="col">
    </div>
    <div id="top" class="col-6 styling">
      <h1 class="spacing">Create Account</h1>
    </div>
    <div class="col">
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background" >
      <%= form_with model: @user do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: 'name', class: "form-control", id: "name" %>
        <br>
        <%= f.label :email %>
        <%= f.text_field :email, placeholder: 'email', class: "form-control", id: "exampleInputEmail1", ariadescribedby: "emailHelp" %>
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          <br>
          <%= f.label :password %>
        <%= f.password_field :password, placeholder: 'password', class: "form-control", id: "password" %>
        <br>
        <%= f.submit "Create User", id: "button", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- shows current user profile -->
<div class="container-fluid">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p top">
      <div class="header_two">
       <h4 >Welcome to your Profile </h4>
       <h4><%= @user.name %></h4>
       </div>
    </div>
    <div class="col">
    </div>
  </div>
  <!-- end of row -->
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding">
        <h4>Account Details</h4>
        <p class="left">Email: <%= @user.email %> </p>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
   <!-- end of row -->
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p ">
      <% if user_signed_in_? && current_user == @user %>
        <div class="padding">
          <%= form_with model: Post.new do |f| %>
          <%= f.label :Title %>
          <br>
          <%= f.text_field :title, placeholder: 'title', class: "form-control", id: "title" %>
            <br>
           <%= f.label :Content %>
           <br>
          <%= f.text_field :content, placeholder: 'content', class: "form-control", id:"content" %>
          <br>
          <%= f.submit "Create Post", class: "btn btn-primary", id: "button_three" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="col">
    </div>
  </div>
  <!-- end of row -->
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding">
        <h4>Posts</h4>
      </div>
      <div class="posts padding left post_o">
          <% @user.posts.reverse.each do |post| %>
              <%= render post %>
              <% if user_signed_in_? && current_user == @user %>
               <%= link_to image_tag("delete-icon.png", class: "format"), post,  method: :delete %>
                <%= link_to image_tag("edit.png", class: "format"), edit_post_path(post) %>
              <% end %> 
            <% end %>
      </div>
      
    </div>
    <div class="col">
      <div class="background_p padding">
        <h4 >Fellow Travelers</h4>
      </div>
      <div class="size background_p">
            <% @user_all.each do |user| %>
              <p class="font"></p>
                <%= link_to user.name, user %>
            <% end %></p>
      </div>
    </div>
  </div>
  <!-- end of row -->
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 background_p">
      <div class="padding padding_b">
        <% if user_signed_in_? && current_user == @user %>
          <%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-primary" %>
        <% else %>
          <%= link_to "My Profile", current_user, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col">
      3 of 3
    </div>
<!-- end of container -->
</div>